<?php

namespace Admin\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Count all Article
     *
     * @return int
     */
    public function countAll()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
