<?php

namespace Admin\BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Count all Category
     *
     * @return int
     */
    public function countAll()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('count(c.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
